### ISSUE TITLE
Better authorization failure feedback

### ISSUE THREAD

**Issue by Assios** [Samfundet/Samfundet#53] opened 2016-04-04 20:38 UTC
aleksanb commented on 22 Sep 2014: "Currently, when one accesses a protected resource without the required permissions, one is simply redirected to the login screen.

The message received should be 'insufficient permissions' instead of a generic 'login' to access this resource message, when the user is logged in."

**Comment by eirikvaa** [comment] 2019-09-10 18:42
Duplicate of #20

**Closed as completed by eirikvaa** 2019-09-10 18:42 UTC
