### ISSUE TITLE
_upcoming_events should be renamed

### ISSUE THREAD

**Issue by stianste** [Samfundet/Samfundet#27] opened 2016-04-04 19:03 UTC
Better things would be for an instance _frontpage_items, or _frontpage_content (referring to that event and article publications are editorial "content"). When blog posts are part of the front page refering to the displayed items as "events" doesn't make sense any more, and also "upcoming" looses its feeling of sense when the context is a blog post...

**Comment by eirikvaa** [comment] 2019-09-10 18:30
Duplicate of #22

**Closed as completed by eirikvaa** 2019-09-10 18:30 UTC
Labels: good first issue
